import Link from "next/link";

const features = [
  {
    emoji: "📓",
    title: "Prayer Journal",
    description:
      "Log your prayers with categories like Family, Health, Finances, and more. Tag who you're praying for.",
  },
  {
    emoji: "✅",
    title: "Track Answered Prayers",
    description:
      "Mark prayers as answered and watch your list grow. See how God has moved in your life.",
  },
  {
    emoji: "🕐",
    title: "Guided ACTS Sessions",
    description:
      "Timed prayer sessions using the ACTS model - Adoration, Confession, Thanksgiving, Supplication.",
  },
  {
    emoji: "🤖",
    title: "AI-Powered Prompts",
    description:
      "Each session includes scripture and prompts generated by AI, tailored to your topic or verse.",
  },
  {
    emoji: "🔗",
    title: "Share Prayer Requests",
    description:
      "Share any prayer via a public link. Others can click 'I'm praying for this' - no account needed.",
  },
  {
    emoji: "👥",
    title: "Prayer Groups",
    description:
      "Create private prayer groups. Invite members by email. Share requests and pray for each other.",
  },
];

export default function LandingPage() {
  return (
    <div className="min-h-screen bg-brand-black">
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: JSON.stringify({
            "@context": "https://schema.org",
            "@type": "SoftwareApplication",
            name: "The Prayer Room",
            applicationCategory: "ReligiousApplication",
            operatingSystem: "Web",
            offers: {
              "@type": "Offer",
              price: "0",
              priceCurrency: "USD",
            },
            description:
              "Personal prayer journal, guided ACTS prayer sessions, and prayer groups. Free for everyone.",
          }),
        }}
      />

      <header className="relative overflow-hidden">
        <div className="max-w-4xl mx-auto px-4 py-20 text-center">
          <span className="text-6xl mb-6 block">🙏</span>
          <h1 className="text-4xl md:text-5xl font-bold text-brand-white mb-4">
            The Prayer Room
          </h1>
          <p className="text-xl text-brand-muted mb-2 max-w-2xl mx-auto">
            Your personal prayer companion.
          </p>
          <p className="text-lg text-brand-gold mb-8">
            Journal. Pray. Share. Together.
          </p>
          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <Link
              href="/sign-up"
              className="px-8 py-4 bg-brand-gold text-brand-black font-bold rounded-xl text-lg hover:bg-brand-gold-light transition-colors"
            >
              Get Started - It&apos;s Free
            </Link>
            <Link
              href="/sign-in"
              className="px-8 py-4 border border-brand-border text-brand-white font-medium rounded-xl text-lg hover:border-brand-gold/30 transition-colors"
            >
              Sign In
            </Link>
          </div>
        </div>
      </header>

      <section className="max-w-4xl mx-auto px-4 py-16 text-center">
        <h2 className="text-2xl font-bold text-brand-white mb-8">
          How It Works
        </h2>
        <div className="flex flex-col md:flex-row gap-8 justify-center">
          <div className="flex-1">
            <span className="text-4xl mb-3 block">1</span>
            <h3 className="font-semibold text-brand-white mb-1">
              Log your prayers
            </h3>
            <p className="text-brand-muted text-sm">
              Write what&apos;s on your heart. Pick a category. Tag who you&apos;re praying for.
            </p>
          </div>
          <div className="flex-1">
            <span className="text-4xl mb-3 block">2</span>
            <h3 className="font-semibold text-brand-white mb-1">
              Enter guided prayer
            </h3>
            <p className="text-brand-muted text-sm">
              Pick a time, get scripture-based prompts, and walk through the ACTS model.
            </p>
          </div>
          <div className="flex-1">
            <span className="text-4xl mb-3 block">3</span>
            <h3 className="font-semibold text-brand-white mb-1">
              Pray together
            </h3>
            <p className="text-brand-muted text-sm">
              Share requests publicly or in private groups. See who&apos;s praying with you.
            </p>
          </div>
        </div>
      </section>

      <section className="max-w-4xl mx-auto px-4 py-16">
        <h2 className="text-2xl font-bold text-brand-white text-center mb-12">
          Everything You Need
        </h2>
        <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
          {features.map((feature) => (
            <div
              key={feature.title}
              className="bg-brand-card border border-brand-border rounded-xl p-6"
            >
              <span className="text-3xl mb-3 block">{feature.emoji}</span>
              <h3 className="text-lg font-semibold text-brand-white mb-2">
                {feature.title}
              </h3>
              <p className="text-brand-muted text-sm">{feature.description}</p>
            </div>
          ))}
        </div>
      </section>

      <section className="max-w-4xl mx-auto px-4 py-16 text-center">
        <div className="bg-brand-card border border-brand-gold/30 rounded-2xl p-8 max-w-sm mx-auto">
          <p className="text-brand-gold text-sm font-medium mb-2">
            ALWAYS FREE
          </p>
          <p className="text-5xl font-bold text-brand-white mb-2">$0</p>
          <p className="text-brand-muted mb-6">
            Free forever. A gift for those who seek.
          </p>
          <Link
            href="/sign-up"
            className="block w-full py-3 bg-brand-gold text-brand-black font-semibold rounded-xl hover:bg-brand-gold-light transition-colors"
          >
            Enter The Prayer Room
          </Link>
        </div>
      </section>

      <section className="max-w-4xl mx-auto px-4 py-8 text-center">
        <p className="text-brand-muted text-sm">
          Available on the{" "}
          <a
            href="https://tvrapp.app"
            target="_blank"
            rel="noopener noreferrer"
            className="text-brand-gold hover:text-brand-gold-light"
          >
            TVR App Store
          </a>
        </p>
      </section>

      <footer className="border-t border-brand-border py-8 text-center">
        <p className="text-brand-muted text-sm">
          &copy; {new Date().getFullYear()} The Prayer Room. A TVR App Store
          Product.
        </p>
      </footer>
    </div>
  );
}
